login:
    path: /
    controller: App\Controller\LoginController::index
login-register:
    path: /register
    controller: App\Controller\LoginController::showRegister
    methods: GET
login-register-form:
    path: /register
    controller: App\Controller\LoginController::register
    methods: POST
app_logout:
    path: /logout
    methods: GET
dashboard-index:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: GET
calendar-index:
    path: /calendar
    controller: App\Controller\HomeController::index
    methods: GET