login:
    path: /
    controller: App\Controller\LoginController::index
app_logout:
    path: /logout
    methods: GET
dashboard-index:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: GET
planning-index:
    path: /calendar
    controller: App\Controller\PlanningController::index
    methods: GET
event-feed:
    path: /calendar/feed
    controller: App\Controller\PlanningController::eventFeed
    methods: GET
event-save:
    path: /calendar
    controller: App\Controller\PlanningController::createEvent
    methods: POST
event-update:
    path: /calendar/save
    controller: App\Controller\PlanningController::updateEvent
    methods: POST
event-delete:
    path: /calendar/delete
    controller: App\Controller\PlanningController::deleteEvent
    methods: POST
contact-index:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: GET
contact-feed:
    path: /contact/feed
    controller: App\Controller\ContactController::contactDataFeed
    methods: POST
# contact-feed-get:
#     path: /contact/feed
#     controller: App\Controller\ContactController::eventDataFeed
#     methods: GET
contact-create:
    path: /contact
    controller: App\Controller\ContactController::newContact
    methods: POST
contact-show:
    path: /contact/{id}
    controller: App\Controller\ContactController::showContact
    methods: GET
contact-update:
    path: /contact/save/{id}
    controller: App\Controller\ContactController::updateContact
    methods: POST
contact-populate:
    path: /contact/populate/{count}
    controller: App\Controller\ContactController::populate
    methods: GET
    defaults:
        id: 1

user-profile:
    path: /user
    controller: App\Controller\UserController::index
    methods: GET
user-update:
    path: /user
    controller: App\Controller\UserController::update
    methods: POST

admin-index:
    path: /admin
    controller: App\Controller\AdminController::index
    methods: GET
admin-extrafields-save:
    path: /admin
    controller: App\Controller\AdminController::newExtrafields
    methods: POST
admin-register:
    path: /admin/register
    controller: App\Controller\LoginController::register
    methods: POST